#!/bin/zsh
# Config common to both bashrc and zshrc

##############################################################################
#
#				ENVIRONMENTAL VARIABLES
#
##############################################################################

##############################################################################
#
#				ALIASES
#
##############################################################################

# General
alias findfile='find . -name'
# alias ls='ls -lhGp --group-directories-first' # Linux
alias ls='ls -lhGp' # OSX
alias resethosts='mv ~/.ssh/known_hosts ~/.ssh/known_hosts.bak'
alias tmux='tmux -2'

# Digital Ocean Server
alias doserver='ssh root@45.55.170.64'

# Docker
alias dockerclean='docker rm `docker ps -aq`'
# alias dockercleanimages='docker rmi `docker images | grep "<none>" | awk "{print $3}"`'
alias dockercleanimages='docker rmi `docker images -f "dangling=true" -q`'

# Java
alias javaclean='rm *.class'

# Python
alias pypath='export PYTHONPATH=$(pwd)'

##############################################################################
#
#				FUNCTIONS
#
##############################################################################

##### General

function findinfile {
    if [[ ($# -lt 1) || ($1 = '-h') ]]; then
      echo 'usage: findinfile [-h]|[<file_pattern> <target_string>]'
    else
      grep --include=$1 -rn . -e $2
    fi
}

##### Docker

# Start new instance of docker image, running bash instead of default entrypoint
function docker_bash {
    docker run -it --rm $1 /bin/bash
}

# Start shell in existing docker container
function docker_attach {
    docker exec -it $1 /bin/bash
}

##### Python

function pyclean {
  find $1 -name "*.pyc" | xargs rm
  find . -name "__pycache__" | xargs rmdir
}

# Activate virtualenv
function venv {
    . $1/bin/activate
}

# New virtualenv
function nvenv {
    echo Creating/activating new virtualenv $1
    virtualenv -p python2.7 $1
    venv $1
}

# New virtualenv
function nvenv3 {
    echo Creating/activating new virtualenv $1
    virtualenv -p python3 $1
    venv $1
}

##############################################################################
#
#				LOAD CONFIGS
#
##############################################################################

# Load OSX config
[ -f ~/.osx_config_leo ] && echo "Loading OSX config" && source ${HOME}/.osx_config_leo

# Load CERN/CMS config
[ -f ~/.cms_config_leo ] && echo "Loading CMS config" && source ${HOME}/.cms_config_leo

# Load JW Player config
[ -f ~/.jw_config_leo ] && echo "Loading JW Config" && source ${HOME}/.jw_config_leo
